---
# file: roles/nrpe/handlers/main.yml

- name: Start nrpe
  service: name=nagios-nrpe-server state=started enabled=yes

- name: Restart nrpe
  service: name=nagios-nrpe-server state=restarted enabled=yes