---
# file: roles/nrpe/tasks/main.yml

- name: Installing nrpe
  apt: name={{ item }} state=latest
  with_items:
    - nagios-nrpe-server
    - nagios-plugins
    - libapr1
    - nagios-plugins-contrib
  tags:
    - nrpe

- name: Create the /var/cache/nagios directory
  file:
    path: /var/cache/nagios
    state: directory
    owner: nagios
  notify: Restart nrpe
  tags:
    - nrpe

- name: Set our nagios box as the only allowed host
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: "^allowed_hosts="
    line: "allowed_hosts=127.0.0.1,192.168.123.0/24"
  notify: Restart nrpe
  tags:
    - nrpe

- name: Allow commands with arguments
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: "^dont_blame_nrpe="
    line: "done_blame_nrpe=1"
  notify: Restart nrpe

- name: Populate MySQL specific NRPE commands
  template: src=templates/mysql-nrpe.cfg.j2 dest=/etc/nagios/nrpe.d/mysql-nrpe.cfg
  when:
    - nagios_sql_username is defined
    - nagios_sql_password is defined
  tags:
    - nrpe