---
# file: playbook.yml

- hosts: nagios.yourdomain.local
  become: yes
  roles:
    - common
    - apache
    - php
    - nagios
    - apache-vhost

- hosts: sql.yourdomain.local
  become: yes
  roles:
    - common
    - mysql
    - nrpe